// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package connectorkitdemo.actions;

import com.mendix.core.Core;
import com.mendix.core.objectmanagement.member.MendixAutoNumber;
import com.mendix.core.objectmanagement.member.MendixObjectReference;
import com.mendix.core.objectmanagement.member.MendixObjectReferenceSet;
import com.mendix.logging.ILogNode;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObjectMember;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;

public class CreateObjectList extends CustomJavaAction<java.util.List<IMendixObject>>
{
	private java.lang.String ResultEntity;
	private IMendixObject DefaultObject;
	private java.lang.String InitializationMicroflow;
	private java.lang.Long ListSize;

	public CreateObjectList(IContext context, java.lang.String ResultEntity,
							IMendixObject DefaultObject, java.lang.String InitializationMicroflow,
							java.lang.Long ListSize)
	{
		super(context);
		this.ResultEntity = ResultEntity;
		this.DefaultObject = DefaultObject;
		this.InitializationMicroflow = InitializationMicroflow;
		this.ListSize = ListSize;
	}

	@Override
	public java.util.List<IMendixObject> executeAction() throws Exception
	{
		// BEGIN USER CODE
        logger.info(String.format("creating list of %d %s objects, initialized by %s",
                this.ListSize, this.ResultEntity, this.InitializationMicroflow));
        // Create a list to return with all the instantiated objects
        ArrayList<IMendixObject> resultList = new ArrayList<IMendixObject>();
        for (int i = 0; i <= this.ListSize; i = i + 1) {
            // create new object of type resultentity
            IMendixObject newObject = Core.instantiate(getContext(), this.ResultEntity);
            if (this.DefaultObject != null) {
                // copy values from default object
                Map<String, ? extends IMendixObjectMember<?>> members = DefaultObject.getMembers(getContext());
                for (String key : members.keySet()) {
                    IMendixObjectMember<?> m = members.get(key);
                    if (!(m instanceof MendixObjectReference) && !(m instanceof MendixObjectReferenceSet) &&
                            !(m instanceof MendixAutoNumber) && !(m.isVirtual())) {
                        newObject.setValue(getContext(), key, m.getValue(getContext()));
                    }
                }
            }
            // run the specified initialization microflow
            Core.execute(getContext(), this.InitializationMicroflow, newObject);
            // add new object to list
            resultList.add(newObject);
        }
        return resultList;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public java.lang.String toString()
	{
		return "CreateObjectList";
	}

	// BEGIN EXTRA CODE
    private static final ILogNode logger = Core.getLogger(CreateObjectList.class.getName());
	// END EXTRA CODE
}
